services:
  db:
    image: mongo:4.2.23
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    volumes:
      - db:/data/db
  api:
    build: 
      dockerfile: 'Dockerfile.dev'
    depends_on:
      - db
    environment:
      - MONGODB_URL=mongodb://db
      - MONGODB_DBNAME=${MONGODB_DBNAME}
      - API_DEPOT_URL=${API_DEPOT_URL}
      - API_ETABLISSEMENTS_PUBLICS=${API_ETABLISSEMENTS_PUBLICS}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_BCC=${SMTP_BCC}
      - SHOW_EMAILS=${SHOW_EMAILS}
      - FC_SERVICE_URL=${FC_SERVICE_URL}
      - FC_FS_ID=${FC_FS_ID}
      - FC_FS_SECRET=${FC_FS_SECRET}
      - FC_FS_CALLBACK=${FC_FS_CALLBACK}
      - SESSION_SECRET=${SESSION_SECRET}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - BAN_API_URL=${BAN_API_URL}
      - BAN_API_TOKEN=${BAN_API_TOKEN}
      - NOTIFY_BAN=${NOTIFY_BAN}
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      - ./lib:/app/lib
      - ./migrations:/app/migrations
      - ./scripts:/app/scripts
      - ./server.js:/app/server.js
      - ./cron.js:/app/cron.js
volumes:
  db:
